print("Hello, Git Project!")
print("New Feature added")
print("Added additional changes")
print("Feature branch logic")
print("Making changes without commit")
print("Doing wrong commit")
print("Reset wrong commit and now adding the right one")
